export const Images = {
  earth: require('../assets/images/earth.png'),
  pageBackground: require('../assets/images/pageBG.png'),
  appicon: require('../assets/images/E-Attendance.png'),
  drawerNav: require('../assets/images/drawerNav.png'),
  eyeclose: require('../assets/images/eyeclose.png'),
  eyeopen: require('../assets/images/eyeopen.png'),
  notificationBell: require('../assets/images/notificationBell.png'),
  successTick: require('../assets/images/successTick.png'),
  tab1: require('../assets/images/tab1.png'),
  tab2: require('../assets/images/tab2.png'),
  tab3: require('../assets/images/tab3.png'),
  tab4: require('../assets/images/tab4.png'),
  tab5: require('../assets/images/tab5.png'),
  tab6: require('../assets/images/tab6.png'),
  tab7: require('../assets/images/tab7.png'),
  googleplay: require('../assets/images/google-play.png'),

  backbutton1: require('../assets/images/backbutton1.png'),
  downArrow: require('../assets/images/downArrow.png'),
  lock: require('../assets/images/lock.png'),
  option: require('../assets/images/option.png'),
  delete: require('../assets/images/delete.png'),

  drawer1: require('../assets/images/tab3.png'),
  drawer2: require('../assets/images/drawer2.png'),
  drawer4: require('../assets/images/tab2.png'),
  drawer6: require('../assets/images/drawer6.png'),
  drawerbg: require('../assets/images/drawerbg.png'),
  cross: require('../assets/images/Cross.png'),
  close: require('../assets/images/close.png'),
  location: require('../assets/images/location.png'),
  clock: require('../assets/images/clock.png'),
  uploadImage: require('../assets/images/uploadImage.png'),
  map: require('../assets/images/map.png'),
  s: require('../assets/images/s.png'),
  msgBg: require('../assets/images/msgBg.png'),
  tick: require('../assets/images/tick.png'),
  mailbox: require('../assets/images/mailbox.png'),
  downarrow2: require('../assets/images/downarrow2.png'),
  profilepic: require('../assets/images/profilepic.png'),
  pdf: require('../assets/images/pdf.png'),
  logout: require('../assets/images/exit.png'),
  camera: require('../assets/images/camera.png'),
  noTask: require('../assets/images/noTask.png'),
  refreshicon: require('../assets/images/flip.png'),
  refresh: require('../assets/images/refresh.png'),
  roadmap: require('../assets/images/roadmap.png'),
  language: require('../assets/images/language.png'),
  call: require('../assets/images/call.png'),
  wb_logo: require('../assets/images/wb_logo.png'),
  addTask: require('../assets/images/addTask.png'),
  success: require('../assets/images/success.png'),
  fail: require('../assets/images/fail.png'),
  alert: require('../assets/images/alert.png'),
  greenbg: require('../assets/images/greenbg.jpg'),
};

export const Colors = {
  white: '#FFFFFF',
  fontWhite: '#FFFAEC',
  black: '#000000',
  red: '#E94343',
  orange: '#FFA500',
  green: '#89C438',
  lightYellow: '#FFFFC5',
  skyblue: '#42C5EA',
  inputGreyBorder: '#EFEFEF',
  textInputColor: '#1B1831',
  darkblue: '#1B1831',
  tintGrey: '#A5A5A5',
  greytext: '#B4B3BB',
  greytext2: '#504F4F',
  lightgreybg: '#B4B3BB',
  lightgreybg2: 'rgb(249,249,249)',
  lightgreen: '#bdffc3',
  lightred: '#ffc0bd',
  backgroundWhite: 'rgb(244,244,244)',
  lightBlue: 'rgb(232,247,253)',
  grey: '#7D7C8A',
  bgColor: '#34495e',
};

export const Fonts = {
  MulishBold: 'Mulish-Bold',
  MulishItalic: 'Mulish-Italic',
  MulishLight: 'Mulish-Light',
  MulishMedium: 'Mulish-Medium',
  MulishRegular: 'Mulish-Regular',
  MulishSemiBold: 'Mulish-SemiBold',
  MulishExtraBold: 'Mulish-ExtraBold',
  MulishBlack: 'Mulish-Black',
};
